version: '3'

services:
  tsrtmp_db:
    image: mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "./mysql/mysql:/var/lib/mysql"
      - "./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"
    ports:
      - 3306:3306
    networks:
      - webnet

  replay:
    depends_on:
      - tsrtmp_db
    image: replay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      TSRTMP_DB_HOST: tsrtmp_db
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"
    ports:
      - 5000:5000
    networks:
      - webnet

  record:
    depends_on:
      - tsrtmp_db
    image: record
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      TSRTMP_DB_HOST: tsrtmp_db
    volumes:
      - "/var/www/html:/var/www/html"
      - "./record_conf:/app/record_conf"
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"
    networks:
      - webnet
    ports:
      - 9999:9999
      - 10000-21000:10000-21000/udp
      

networks:
  webnet:
