#!/bin/bash
### BEGIN INIT INFO
# Provides:	record
# Required-Start:	$remote_fs $syslog mysql
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start video record at boot time
# Description:		Enable service provided by daemon
### END INIT INFO

APP_PATH=/home/share/video_record/
NAME="tsserver"
PIDFILE=$APP_PATH"tsserver.pid"
SCRIPT=$APP_PATH"tsserver"

. /lib/lsb/init-functions

do_start()
{
  $SCRIPT 1>&2 >/dev/null &
}

do_stop()
{
  pkill $NAME
}
case "$1" in
  start )
    do_start
    ;;
  stop )
    do_stop
    ;;
  restart )
    do_stop
    echo "stop done. sleep for 1 second"
    sleep 1
    do_start
    echo "start ok"
    ;;
  status)
    status_of_proc -p "$PIDFILE" "$SCRIPT" "$NAME" && exit 0 || exit $?
    ;;
esac
